version: '3.8'
services:

  creatorready:
    build:
      context: .
      dockerfile: dockerfile.app1
    ports:
      - "8001:8001"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  refinerready:
    build:
      context: .
      dockerfile: dockerfile.app2
    ports:
      - "8002:8002"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  modifierready:
    build:
      context: .
      dockerfile: dockerfile.app3
    ports:
      - "8003:8003"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
